### ISSUE TITLE
Adding more dependencies

### ISSUE THREAD

**Issue by stippi** [Barteks2x/SWT-NativeImage-GitgubActions-example#1]
Hello. This project is pretty neat!

I was wondering how I could add more dependencies, for example JFace. Is this how I should do it in `build.gradle`?

```diff
dependencies {
    linux_amd64("org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64:3.114.0") {
        transitive = false
    }
    ...
    shadow group: 'com.google.code.gson', name: 'gson', version: '2.3.1'
+   shadow group: 'org.eclipse.platform', name: 'org.eclipse.jface', version: '3.12.2'

    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation "org.eclipse.platform:org.eclipse.swt:3.108.0"
}

```

This works fine in IntelliJ, but not during the native image builds in the GitHub action. I was wondering if it fails for the same reason as the macOS build with the official .jar, since the JFace jar is likely also compiled with Eclipse Java compiler. But the other builds (Windows, Linux) fail just the same. I can provide more info from the logs, if needed, but since I am completely new to Gradle, maybe it is a quick hint.

Thanks very much for any help!

**Comment by Niko-sk2x** [comment]
Sorry for the late reply, I missed the notification.

The dependencies have to compile on native image for this to keep working, obviously. I haven't used jface but if it has a native library part of it, it would likely require a bit more configuration. Logs would provide more information. Also the reason it was only one platform that failed for SWT itself is that SWT has different code for each platform, and only that one platform triggered the issue. If jface triggers the same issue but in platform-independent part of code, it will have the same issue but on all platforms.

I don't think I'm going to put in the work to actually do that anytime soon, since this project is split out part of a different project that I originally needed it for, and it's unlikely I will need jface in it, or a significant update to the build setup.

**Comment by stippi** [comment]
Understood, thanks a lot!
